community_mail:
  url: /communityMail/:id
  param: { module: communityMail, action: form }
  class: sfDoctrineRoute
  options: { type: object, model: Community }
  requirements:
    id: \d+
    sf_method: [get, post]

community_mail_send:
  url: /communityMail/:id/send
  param: { module: communityMail, action: send }
  class: sfDoctrineRoute
  options: { type: object, model: Community }
  requirements:
    id: \d+
    sf_method: post