community_message:
  url: /communityMessage/:id
  param: { module: communityMessage, action: form }
  class: sfDoctrineRoute
  options: { type: object, model: Community }
  requirements:
    id: \d+
    sf_method: [get, post]

community_message_send:
  url: /communityMessage/:id/send
  param: { module: communityMessage, action: send }
  class: sfDoctrineRoute
  options: { type: object, model: Community }
  requirements:
    id: \d+
    sf_method: post